# 服务主要要配置
## http配置
http:
  port: '9003' # http端口

## 任务配置
task:
  log_retention: '720h' # 日志保留时间，最小有效值 24h; 有效的单位："s", "m", "h"。
  task_del_retention: '720h' # 删除（已关闭）任务保留时间，最小有效值 24h; 有效的单位："s", "m", "h"。
## 加密
crypto:
  secret: '12345678' # 秘钥 长度必须为8位字符，空表示不加密